steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/third-camera-487000-k9/navio', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/third-camera-487000-k9/navio']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'navio'
      - '--image=gcr.io/third-camera-487000-k9/navio'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--clear-secrets'
      - '--update-env-vars=GCP_PROJECT_ID=third-camera-487000-k9,GCP_REGION=us-central1,GEMINI_MODEL=gemini-2.5-flash'

options:
  logging: CLOUD_LOGGING_ONLY
